#!/usr/bin/env python3

from setuptools import setup

with open("README.md", "r") as fh:
    long_description = fh.read()
    setup(
        name='Pypal',
        author='Daniel Turner',
        version='0.0.1',
        packages=['pypal'],
        package_dir={'pypal': 'src'},
        description='Python port of Pipal for password analytics',
        long_description=long_description,
        long_description_content_type="text/markdown",
        url="https://github.com/f0cker/pypal",
        #package_data={'pypal': ['lists/']},
        #include_package_data=True,
        install_requires=[
		'altair==5.0.1',
		'attrs==23.1.0',
		'click==8.1.4',
		'cycler==0.11.0',
		'fuzzyset==0.0.19',
		'importlib-resources==6.0.0',
		'Jinja2==3.1.2',
		'joblib==1.3.1',
		'jsonschema==4.18.0',
		'jsonschema-specifications==2023.6.1',
		'kiwisolver==1.4.4',
		'Levenshtein==0.21.1',
		'MarkupSafe==2.1.3',
		'matplotlib==3.4.3',
		'nltk==3.8.1',
		'numpy==1.24.4',
		'pandas==2.0.3',
		'Pillow==10.0.1',
		'pkgutil-resolve-name==1.3.10',
		'Pypal==0.0.1',
		'pyparsing==3.1.0',
		'python-dateutil==2.8.2',
		'python-Levenshtein==0.21.1',
		'pytz==2023.3',
		'rapidfuzz==3.1.1',
		'referencing==0.29.1',
		'regex==2023.6.3',
		'rpds-py==0.8.10',
		'six==1.16.0',
		'texttable==1.6.7',
		'toolz==0.12.0',
		'tqdm==4.65.0',
		'typing-extensions==4.7.1',
		'tzdata==2023.3',
		'vega-datasets==0.9.0',
		'zipp==3.16.0',
            ],
        classifiers=[
            "Programming Language :: Python :: 3",
            "License :: OSI Approved :: MIT License",
            "Operating System :: POSIX",
            "Operating System :: MacOS",
            ],
        )
